import { Geist, Geist_Mono,Roboto,Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  style: ["normal"],
  weight: ["400", "500", "600", "700"],
});

// const roboto = Roboto({
//   variable: "--font-roboto",
//   subsets: ["latin"],
//   weight: ["400", "500", "700"], 
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased`}
      >
        <Navbar />
        <div className="min-h-[calc(100vh-117px)] max-w-7xl m-auto">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
